# Generated by Django 5.0.3 on 2024-04-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salgrade',
            fields=[
                ('grade', models.IntegerField(primary_key=True, serialize=False)),
                ('losal', models.DecimalField(decimal_places=4, max_digits=10)),
                ('hisal', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='dept',
            name='DNAME',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('EMPNO', models.IntegerField(primary_key=True, serialize=False)),
                ('ENAME', models.CharField(max_length=100)),
                ('JOB', models.CharField(max_length=100)),
                ('HIREDATE', models.DateField()),
                ('SAL', models.DecimalField(decimal_places=3, max_digits=10)),
                ('COMM', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('DEPTNO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('MGR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp')),
            ],
        ),
    ]
